### PR TITLE
fixed email link

### LINKED ISSUE #5: link on mail does not work
The link on the email button does not work, it sends to a non working page (uses the email as the path of the page)

### PR DESCRIPTION
**Pull request by lucamattiazzi**
fix #5

### CODE REVIEW

File: src/constants/index.js [hunk 1]
```diff
@@ -13,7 +13,7 @@ export const LATEST = 'latest'
 export const RANDOM = 'random'
 
 export const SOCIALS = {
-  Email: 'kylie@kyliestewart.tech',
+  Email: 'mailto:kylie@kyliestewart.tech',
```
Comment (kale-stew) [inline src/constants/index.js]: I don't want to store this extra browser stuff in my constants, so I'm going to prefer a route that just modifies the broken button in place. Going to make that small change to this PR and merge it in. Thank you for opening :-)

Comment (lucamattiazzi) [reply src/constants/index.js]: it does make more sense your way
